-- ============================================================================
-- INSURANCE AI HUB - Production Deployment
-- Script 08: RBAC (Database Roles & Grants)
-- ============================================================================
-- Run as: ACCOUNTADMIN
-- Depends on: 02_tables.sql, 03_views.sql
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE INSURANCE_AI_HUB;

-- ############################################################################
-- SECTION 1: CREATE DATABASE ROLES
-- ############################################################################

-- Role hierarchy (top-down):
-- INSURANCE_ADMIN_ROLE
--   ├── INSURANCE_DATA_STEWARD_ROLE
--   ├── INSURANCE_EXEC_ROLE
--   │     └── INSURANCE_ANALYST_ROLE
--   ├── INSURANCE_UW_ROLE
--   │     └── INSURANCE_ANALYST_ROLE
--   └── INSURANCE_CLAIMS_ROLE
--         └── INSURANCE_ANALYST_ROLE

CREATE DATABASE ROLE IF NOT EXISTS INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE;
CREATE DATABASE ROLE IF NOT EXISTS INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
CREATE DATABASE ROLE IF NOT EXISTS INSURANCE_AI_HUB.INSURANCE_EXEC_ROLE;
CREATE DATABASE ROLE IF NOT EXISTS INSURANCE_AI_HUB.INSURANCE_UW_ROLE;
CREATE DATABASE ROLE IF NOT EXISTS INSURANCE_AI_HUB.INSURANCE_CLAIMS_ROLE;
CREATE DATABASE ROLE IF NOT EXISTS INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE;


-- ############################################################################
-- SECTION 2: ROLE HIERARCHY (Grant child roles to parent roles)
-- ############################################################################

-- Admin inherits all child roles
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE;
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_EXEC_ROLE TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE;
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_UW_ROLE TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE;
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_CLAIMS_ROLE TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE;

-- Exec, UW, Claims inherit Analyst
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_EXEC_ROLE;
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_CLAIMS_ROLE;
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_UW_ROLE;


-- ############################################################################
-- SECTION 3: GRANTS - ANALYST ROLE (base read access to Analytics)
-- ############################################################################

GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_AI_HUB.ANALYTICS TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;

-- Tables
GRANT SELECT ON TABLE INSURANCE_AI_HUB.ANALYTICS.AGENTS TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.ANALYTICS.AGENT_AUDIT_LOG TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.ANALYTICS.BILLING TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.ANALYTICS.CLAIMS TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.ANALYTICS.POLICIES TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;

-- Views
GRANT SELECT ON VIEW INSURANCE_AI_HUB.ANALYTICS.VW_AT_RISK_PORTFOLIO TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT SELECT ON VIEW INSURANCE_AI_HUB.ANALYTICS.VW_CLAIMS_PERFORMANCE TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;
GRANT SELECT ON VIEW INSURANCE_AI_HUB.ANALYTICS.VW_CUSTOMER_360 TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE;


-- ############################################################################
-- SECTION 4: GRANTS - DATA STEWARD ROLE (DQ schema access)
-- ############################################################################

GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_AI_HUB.DATA_QUALITY TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE;

GRANT SELECT ON TABLE INSURANCE_AI_HUB.DATA_QUALITY.DQ_RULES TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE;
GRANT SELECT ON TABLE INSURANCE_AI_HUB.DATA_QUALITY.DQ_COLUMN_HEALTH TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE;


-- ############################################################################
-- SECTION 5: GRANTS - CLAIMS ROLE (Documents schema access)
-- ############################################################################

GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_CLAIMS_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_AI_HUB.DOCUMENTS TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_CLAIMS_ROLE;


-- ############################################################################
-- SECTION 6: GRANTS - REMAINING ROLES (Database usage)
-- ############################################################################

GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE;
GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_EXEC_ROLE;
GRANT USAGE ON DATABASE INSURANCE_AI_HUB TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_UW_ROLE;


-- ############################################################################
-- SECTION 7: SERVICE ROLE GRANTS
-- The INSURANCE_SERVICE_ROLE (account role, created in 00_setup.sql) needs
-- the ADMIN database role so agents/tasks can read all schemas.
-- ############################################################################

GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE TO ROLE INSURANCE_SERVICE_ROLE;

-- Service role also needs INSERT on audit log for agent observability
GRANT INSERT ON TABLE INSURANCE_AI_HUB.ANALYTICS.AGENT_AUDIT_LOG TO DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE;


-- ############################################################################
-- SECTION 8: GRANT DATABASE ROLES TO ACCOUNT ROLES
-- Uncomment and adjust for your environment. Without these grants,
-- the database roles exist but no user can activate them.
-- ############################################################################

-- Admin database role -> deploy role (for DDL) and SYSADMIN
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE TO ROLE INSURANCE_DEPLOY_ROLE;
GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ADMIN_ROLE TO ROLE SYSADMIN;

-- Map remaining database roles to your account roles:
-- GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_ANALYST_ROLE TO ROLE <YOUR_ANALYST_ROLE>;
-- GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_EXEC_ROLE TO ROLE <YOUR_EXEC_ROLE>;
-- GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_UW_ROLE TO ROLE <YOUR_UW_ROLE>;
-- GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_CLAIMS_ROLE TO ROLE <YOUR_CLAIMS_ROLE>;
-- GRANT DATABASE ROLE INSURANCE_AI_HUB.INSURANCE_DATA_STEWARD_ROLE TO ROLE <YOUR_STEWARD_ROLE>;

-- ============================================================================
-- END OF 08_rbac.sql
-- ============================================================================
