-- ============================================================================
-- INSURANCE AI HUB - Enhancement Deployment
-- Script 12: Extended Semantic Views (3 new SVs with VQRs)
-- ============================================================================
-- Run as: ACCOUNTADMIN
-- Depends on: 10_extended_tables.sql, 11_extended_views.sql
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE INSURANCE_AI_HUB;
USE SCHEMA ANALYTICS;

-- ############################################################################
-- Semantic View 1: SV_COMPETITIVE_INTEL
-- Competitive pricing analysis
-- ############################################################################

CREATE OR REPLACE SEMANTIC VIEW SV_COMPETITIVE_INTEL
  COMMENT = 'Competitive intelligence model for insurance pricing analysis. Covers product catalog, competitor pricing benchmarks, and pricing optimization scenarios. Enables comparison of our premiums against competitors, market share analysis, and revenue impact projections for pricing strategy changes.'
  TABLES (
    INSURANCE_AI_HUB.ANALYTICS.COMPETITOR_PRICING PRIMARY KEY (BENCHMARK_ID),
    INSURANCE_AI_HUB.ANALYTICS.PRODUCT_CATALOG PRIMARY KEY (PRODUCT_ID),
    INSURANCE_AI_HUB.ANALYTICS.PRICING_SCENARIOS PRIMARY KEY (SCENARIO_ID),
    INSURANCE_AI_HUB.ANALYTICS.POLICIES PRIMARY KEY (POLICY_ID)
  )
  RELATIONSHIPS (
    PRICING_TO_PRODUCT AS COMPETITOR_PRICING(POLICY_TYPE) REFERENCES PRODUCT_CATALOG(POLICY_TYPE)
  )
  FACTS (
    COMPETITOR_PRICING.AVG_PREMIUM AS COMPETITOR_AVG_PREMIUM,
    COMPETITOR_PRICING.MIN_PREMIUM AS COMPETITOR_MIN_PREMIUM,
    COMPETITOR_PRICING.MAX_PREMIUM AS COMPETITOR_MAX_PREMIUM,
    COMPETITOR_PRICING.MARKET_SHARE_PCT AS MARKET_SHARE_PCT,
    COMPETITOR_PRICING.CUSTOMER_RATING AS COMPETITOR_RATING,
    COMPETITOR_PRICING.CLAIMS_RATIO AS COMPETITOR_LOSS_RATIO,
    PRODUCT_CATALOG.BASE_PREMIUM AS BASE_PREMIUM,
    PRODUCT_CATALOG.COVERAGE_LIMIT AS COVERAGE_LIMIT,
    PRICING_SCENARIOS.CURRENT_AVG_PREMIUM AS CURRENT_AVG_PREMIUM,
    PRICING_SCENARIOS.PROPOSED_PREMIUM AS PROPOSED_PREMIUM,
    PRICING_SCENARIOS.PRICE_CHANGE_PCT AS PRICE_CHANGE_PCT,
    PRICING_SCENARIOS.ESTIMATED_RETENTION AS ESTIMATED_RETENTION,
    PRICING_SCENARIOS.PROJECTED_REVENUE AS PROJECTED_REVENUE,
    PRICING_SCENARIOS.REVENUE_IMPACT AS REVENUE_IMPACT,
    PRICING_SCENARIOS.CUSTOMER_IMPACT AS CUSTOMER_IMPACT,
    POLICIES.PREMIUM_AMOUNT AS OUR_PREMIUM_AMOUNT,
    POLICIES.LOSS_RATIO AS OUR_LOSS_RATIO
  )
  DIMENSIONS (
    COMPETITOR_PRICING.BENCHMARK_ID AS BENCHMARK_ID,
    COMPETITOR_PRICING.COMPETITOR_NAME AS COMPETITOR_NAME,
    COMPETITOR_PRICING.POLICY_TYPE AS POLICY_TYPE,
    COMPETITOR_PRICING.PLAN_TIER AS PLAN_TIER,
    COMPETITOR_PRICING.REGION AS REGION,
    COMPETITOR_PRICING.BENCHMARK_DATE AS BENCHMARK_DATE,
    COMPETITOR_PRICING.DATA_SOURCE AS DATA_SOURCE,
    PRODUCT_CATALOG.PRODUCT_ID AS PRODUCT_ID,
    PRODUCT_CATALOG.PRODUCT_NAME AS PRODUCT_NAME,
    PRODUCT_CATALOG.PLAN_TIER AS PRODUCT_TIER,
    PRODUCT_CATALOG.IS_ACTIVE AS PRODUCT_IS_ACTIVE,
    PRICING_SCENARIOS.SCENARIO_ID AS SCENARIO_ID,
    PRICING_SCENARIOS.SCENARIO_NAME AS SCENARIO_NAME,
    PRICING_SCENARIOS.COMPETITIVE_POSITION AS COMPETITIVE_POSITION,
    PRICING_SCENARIOS.RECOMMENDATION AS SCENARIO_RECOMMENDATION,
    POLICIES.POLICY_ID AS POLICY_ID,
    POLICIES.POLICY_STATUS AS POLICY_STATUS
  )
  EXTENSIONS (
    AI_VERIFIED_QUERIES (
      VQR_COMPETITOR_PRICING_BY_TYPE AS (
        QUESTION 'How does our pricing compare to competitors by policy type?'
        SQL $$
          SELECT cp.POLICY_TYPE, cp.COMPETITOR_NAME, cp.AVG_PREMIUM AS COMPETITOR_PREMIUM,
                 AVG(p.PREMIUM_AMOUNT) AS OUR_AVG_PREMIUM,
                 ROUND(AVG(p.PREMIUM_AMOUNT) / NULLIF(cp.AVG_PREMIUM, 0), 2) AS PRICE_RATIO
          FROM INSURANCE_AI_HUB.ANALYTICS.COMPETITOR_PRICING cp
          LEFT JOIN INSURANCE_AI_HUB.ANALYTICS.POLICIES p
            ON cp.POLICY_TYPE = p.POLICY_TYPE AND p.POLICY_STATUS = 'Active'
          GROUP BY cp.POLICY_TYPE, cp.COMPETITOR_NAME, cp.AVG_PREMIUM
          ORDER BY cp.POLICY_TYPE, PRICE_RATIO
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      ),
      VQR_MARKET_SHARE_BY_COMPETITOR AS (
        QUESTION 'What is the market share distribution by competitor?'
        SQL $$
          SELECT COMPETITOR_NAME, POLICY_TYPE, MARKET_SHARE_PCT, CUSTOMER_RATING
          FROM INSURANCE_AI_HUB.ANALYTICS.COMPETITOR_PRICING
          WHERE BENCHMARK_DATE = (SELECT MAX(BENCHMARK_DATE) FROM INSURANCE_AI_HUB.ANALYTICS.COMPETITOR_PRICING)
          ORDER BY MARKET_SHARE_PCT DESC
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      ),
      VQR_PRICING_SCENARIOS_IMPACT AS (
        QUESTION 'What are the pricing scenarios and their revenue impact?'
        SQL $$
          SELECT SCENARIO_NAME, POLICY_TYPE, PLAN_TIER, REGION,
                 CURRENT_AVG_PREMIUM, PROPOSED_PREMIUM, PRICE_CHANGE_PCT,
                 ESTIMATED_RETENTION, PROJECTED_REVENUE, REVENUE_IMPACT,
                 CUSTOMER_IMPACT, COMPETITIVE_POSITION
          FROM INSURANCE_AI_HUB.ANALYTICS.PRICING_SCENARIOS
          ORDER BY ABS(REVENUE_IMPACT) DESC
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      ),
      VQR_OVERPRICED_REGIONS AS (
        QUESTION 'Which regions are we most overpriced compared to competitors?'
        SQL $$
          SELECT cp.REGION, cp.POLICY_TYPE, cp.COMPETITOR_NAME,
                 cp.AVG_PREMIUM AS COMPETITOR_PREMIUM,
                 AVG(p.PREMIUM_AMOUNT) AS OUR_AVG_PREMIUM,
                 ROUND(AVG(p.PREMIUM_AMOUNT) - cp.AVG_PREMIUM, 2) AS PREMIUM_DIFFERENCE
          FROM INSURANCE_AI_HUB.ANALYTICS.COMPETITOR_PRICING cp
          JOIN INSURANCE_AI_HUB.ANALYTICS.POLICIES p
            ON cp.POLICY_TYPE = p.POLICY_TYPE AND p.POLICY_STATUS = 'Active'
          GROUP BY cp.REGION, cp.POLICY_TYPE, cp.COMPETITOR_NAME, cp.AVG_PREMIUM
          HAVING AVG(p.PREMIUM_AMOUNT) > cp.AVG_PREMIUM
          ORDER BY PREMIUM_DIFFERENCE DESC
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      )
    )
  );


-- ############################################################################
-- Semantic View 2: SV_MARKET_INTELLIGENCE
-- Industry trends and benchmarks
-- ############################################################################

CREATE OR REPLACE SEMANTIC VIEW SV_MARKET_INTELLIGENCE
  COMMENT = 'Market intelligence model for insurance industry analysis. Covers market trends, industry benchmarks, year-over-year changes, claim frequency, premium growth, loss ratio benchmarks, and regulatory changes across regions and policy types. Enables comparison of internal performance against market conditions.'
  TABLES (
    INSURANCE_AI_HUB.ANALYTICS.MARKET_TRENDS PRIMARY KEY (TREND_ID),
    INSURANCE_AI_HUB.ANALYTICS.COMPETITOR_PRICING PRIMARY KEY (BENCHMARK_ID)
  )
  RELATIONSHIPS (
    TRENDS_TO_PRICING AS MARKET_TRENDS(POLICY_TYPE) REFERENCES COMPETITOR_PRICING(POLICY_TYPE)
  )
  FACTS (
    MARKET_TRENDS.METRIC_VALUE AS METRIC_VALUE,
    MARKET_TRENDS.PREVIOUS_VALUE AS PREVIOUS_VALUE,
    MARKET_TRENDS.YOY_CHANGE_PCT AS YOY_CHANGE_PCT,
    MARKET_TRENDS.INDUSTRY_BENCHMARK AS INDUSTRY_BENCHMARK,
    MARKET_TRENDS.OUR_PERFORMANCE AS OUR_PERFORMANCE,
    MARKET_TRENDS.VARIANCE_TO_MARKET AS VARIANCE_TO_MARKET,
    COMPETITOR_PRICING.AVG_PREMIUM AS COMPETITOR_AVG_PREMIUM,
    COMPETITOR_PRICING.MARKET_SHARE_PCT AS MARKET_SHARE_PCT
  )
  DIMENSIONS (
    MARKET_TRENDS.TREND_ID AS TREND_ID,
    MARKET_TRENDS.METRIC_NAME AS METRIC_NAME,
    MARKET_TRENDS.POLICY_TYPE AS POLICY_TYPE,
    MARKET_TRENDS.REGION AS REGION,
    MARKET_TRENDS.PERIOD_START AS PERIOD_START,
    MARKET_TRENDS.PERIOD_END AS PERIOD_END,
    MARKET_TRENDS.TREND_DIRECTION AS TREND_DIRECTION,
    MARKET_TRENDS.CONFIDENCE_LEVEL AS CONFIDENCE_LEVEL,
    MARKET_TRENDS.DATA_SOURCE AS DATA_SOURCE,
    COMPETITOR_PRICING.COMPETITOR_NAME AS COMPETITOR_NAME,
    COMPETITOR_PRICING.BENCHMARK_DATE AS BENCHMARK_DATE
  )
  EXTENSIONS (
    AI_VERIFIED_QUERIES (
      VQR_KEY_MARKET_TRENDS AS (
        QUESTION 'What are the key market trends this quarter?'
        SQL $$
          SELECT METRIC_NAME, POLICY_TYPE, REGION, METRIC_VALUE, PREVIOUS_VALUE,
                 YOY_CHANGE_PCT, TREND_DIRECTION, INDUSTRY_BENCHMARK,
                 OUR_PERFORMANCE, VARIANCE_TO_MARKET
          FROM INSURANCE_AI_HUB.ANALYTICS.MARKET_TRENDS
          WHERE PERIOD_END >= DATEADD(MONTH, -3, CURRENT_DATE())
          ORDER BY ABS(YOY_CHANGE_PCT) DESC
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      ),
      VQR_LOSS_RATIO_VS_INDUSTRY AS (
        QUESTION 'How do our loss ratios compare to industry averages?'
        SQL $$
          SELECT POLICY_TYPE, REGION, METRIC_VALUE AS INDUSTRY_LOSS_RATIO,
                 OUR_PERFORMANCE AS OUR_LOSS_RATIO, VARIANCE_TO_MARKET,
                 TREND_DIRECTION
          FROM INSURANCE_AI_HUB.ANALYTICS.MARKET_TRENDS
          WHERE METRIC_NAME = 'LOSS_RATIO'
          ORDER BY VARIANCE_TO_MARKET
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      ),
      VQR_PREMIUM_GROWTH_BY_REGION AS (
        QUESTION 'Which regions are seeing the fastest premium growth?'
        SQL $$
          SELECT REGION, POLICY_TYPE, METRIC_VALUE, YOY_CHANGE_PCT, TREND_DIRECTION
          FROM INSURANCE_AI_HUB.ANALYTICS.MARKET_TRENDS
          WHERE METRIC_NAME = 'PREMIUM_GROWTH_RATE'
          ORDER BY YOY_CHANGE_PCT DESC
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      )
    )
  );


-- ############################################################################
-- Semantic View 3: SV_PRODUCT_MATCHING
-- Product-customer match analysis
-- ############################################################################

CREATE OR REPLACE SEMANTIC VIEW SV_PRODUCT_MATCHING
  COMMENT = 'Product matching model for customer-product recommendations. Covers match scores from multiple strategies (rule-based, similarity, AI-scored), product catalog details, and customer profiles. Enables analysis of match accuracy, product-customer fit, and recommendation effectiveness across segments and risk tiers.'
  TABLES (
    INSURANCE_AI_HUB.ANALYTICS.PRODUCT_MATCH_SCORES PRIMARY KEY (MATCH_ID),
    INSURANCE_AI_HUB.ANALYTICS.PRODUCT_CATALOG PRIMARY KEY (PRODUCT_ID),
    INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
  )
  RELATIONSHIPS (
    MATCH_TO_PRODUCT AS PRODUCT_MATCH_SCORES(PRODUCT_ID) REFERENCES PRODUCT_CATALOG(PRODUCT_ID),
    MATCH_TO_CUSTOMER AS PRODUCT_MATCH_SCORES(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
  )
  FACTS (
    PRODUCT_MATCH_SCORES.MATCH_SCORE AS MATCH_SCORE,
    PRODUCT_MATCH_SCORES.CONFIDENCE AS CONFIDENCE,
    PRODUCT_MATCH_SCORES.RANK_WITHIN_CUSTOMER AS RANK_WITHIN_CUSTOMER,
    PRODUCT_MATCH_SCORES.RECOMMENDED_PREMIUM AS RECOMMENDED_PREMIUM,
    PRODUCT_MATCH_SCORES.PREMIUM_VS_MARKET AS PREMIUM_VS_MARKET,
    PRODUCT_CATALOG.BASE_PREMIUM AS PRODUCT_BASE_PREMIUM,
    PRODUCT_CATALOG.COVERAGE_LIMIT AS PRODUCT_COVERAGE_LIMIT,
    CUSTOMERS.CREDIT_SCORE AS CUSTOMER_CREDIT_SCORE
  )
  DIMENSIONS (
    PRODUCT_MATCH_SCORES.MATCH_ID AS MATCH_ID,
    PRODUCT_MATCH_SCORES.MATCH_STRATEGY AS MATCH_STRATEGY,
    PRODUCT_MATCH_SCORES.CONTRIBUTING_FACTORS AS CONTRIBUTING_FACTORS,
    PRODUCT_MATCH_SCORES.ELIGIBLE AS ELIGIBLE,
    PRODUCT_MATCH_SCORES.INELIGIBILITY_REASON AS INELIGIBILITY_REASON,
    PRODUCT_MATCH_SCORES.SCORED_AT AS SCORED_AT,
    PRODUCT_CATALOG.PRODUCT_ID AS PRODUCT_ID,
    PRODUCT_CATALOG.PRODUCT_NAME AS PRODUCT_NAME,
    PRODUCT_CATALOG.POLICY_TYPE AS POLICY_TYPE,
    PRODUCT_CATALOG.PLAN_TIER AS PLAN_TIER,
    PRODUCT_CATALOG.IS_ACTIVE AS PRODUCT_ACTIVE,
    PRODUCT_CATALOG.FEATURES AS PRODUCT_FEATURES,
    PRODUCT_CATALOG.ELIGIBILITY_RULES AS ELIGIBILITY_RULES,
    CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
    CUSTOMERS.FIRST_NAME AS FIRST_NAME,
    CUSTOMERS.LAST_NAME AS LAST_NAME,
    CUSTOMERS.RISK_TIER AS CUSTOMER_RISK_TIER,
    CUSTOMERS.SEGMENT AS CUSTOMER_SEGMENT,
    CUSTOMERS.STATE AS CUSTOMER_STATE
  )
  EXTENSIONS (
    AI_VERIFIED_QUERIES (
      VQR_TOP_MATCHES_BY_CUSTOMER AS (
        QUESTION 'What are the top product matches for a given customer?'
        SQL $$
          SELECT ms.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.SEGMENT, c.RISK_TIER,
                 pc.PRODUCT_NAME, pc.POLICY_TYPE, pc.PLAN_TIER,
                 ms.MATCH_STRATEGY, ms.MATCH_SCORE, ms.CONFIDENCE,
                 ms.RECOMMENDED_PREMIUM, ms.ELIGIBLE
          FROM INSURANCE_AI_HUB.ANALYTICS.PRODUCT_MATCH_SCORES ms
          JOIN INSURANCE_AI_HUB.ANALYTICS.PRODUCT_CATALOG pc ON ms.PRODUCT_ID = pc.PRODUCT_ID
          JOIN INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS c ON ms.CUSTOMER_ID = c.CUSTOMER_ID
          WHERE ms.ELIGIBLE = TRUE
          ORDER BY ms.CUSTOMER_ID, ms.MATCH_SCORE DESC
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      ),
      VQR_STRATEGY_PERFORMANCE AS (
        QUESTION 'Which matching strategy performs best?'
        SQL $$
          SELECT MATCH_STRATEGY,
                 COUNT(*) AS TOTAL_MATCHES,
                 AVG(MATCH_SCORE) AS AVG_SCORE,
                 AVG(CONFIDENCE) AS AVG_CONFIDENCE,
                 SUM(CASE WHEN ELIGIBLE THEN 1 ELSE 0 END) AS ELIGIBLE_MATCHES,
                 ROUND(SUM(CASE WHEN ELIGIBLE THEN 1 ELSE 0 END)::FLOAT / COUNT(*), 4) AS ELIGIBILITY_RATE
          FROM INSURANCE_AI_HUB.ANALYTICS.PRODUCT_MATCH_SCORES
          GROUP BY MATCH_STRATEGY
          ORDER BY AVG_SCORE DESC
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      ),
      VQR_MATCH_ACCURACY_BY_SEGMENT AS (
        QUESTION 'What is the match accuracy across customer segments?'
        SQL $$
          SELECT c.SEGMENT, c.RISK_TIER, ms.MATCH_STRATEGY,
                 COUNT(*) AS TOTAL,
                 AVG(ms.MATCH_SCORE) AS AVG_MATCH_SCORE,
                 AVG(ms.CONFIDENCE) AS AVG_CONFIDENCE
          FROM INSURANCE_AI_HUB.ANALYTICS.PRODUCT_MATCH_SCORES ms
          JOIN INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS c ON ms.CUSTOMER_ID = c.CUSTOMER_ID
          GROUP BY c.SEGMENT, c.RISK_TIER, ms.MATCH_STRATEGY
          ORDER BY c.SEGMENT, AVG_MATCH_SCORE DESC
        $$
        VERIFIED_AT CURRENT_TIMESTAMP
        VERIFIED_BY 'admin'
      )
    )
  );
