-- ============================================================================
-- INSURANCE AI HUB - Enhancement Deployment
-- Script 19: Extended RBAC Grants for New Objects
-- ============================================================================
-- Run as: ACCOUNTADMIN
-- Depends on: 08_rbac.sql (existing roles), all extended scripts
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE INSURANCE_AI_HUB;

-- ############################################################################
-- Grant SELECT on new ANALYTICS tables to existing roles
-- ############################################################################

-- ANALYST role (base read for ANALYTICS)
GRANT SELECT ON TABLE ANALYTICS.PRODUCT_CATALOG TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE ANALYTICS.COMPETITOR_PRICING TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE ANALYTICS.MARKET_TRENDS TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE ANALYTICS.PRODUCT_MATCH_SCORES TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE ANALYTICS.PRICING_SCENARIOS TO DATABASE ROLE INSURANCE_ANALYST_ROLE;

-- Grant SELECT on new views
GRANT SELECT ON VIEW ANALYTICS.VW_COMPETITIVE_PRICING TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT SELECT ON VIEW ANALYTICS.VW_MATCH_ACCURACY TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT SELECT ON VIEW ANALYTICS.VW_MARKET_ANALYSIS TO DATABASE ROLE INSURANCE_ANALYST_ROLE;

-- Grant USAGE on new semantic views
GRANT SELECT ON SEMANTIC VIEW ANALYTICS.SV_COMPETITIVE_INTEL TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT SELECT ON SEMANTIC VIEW ANALYTICS.SV_MARKET_INTELLIGENCE TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT SELECT ON SEMANTIC VIEW ANALYTICS.SV_PRODUCT_MATCHING TO DATABASE ROLE INSURANCE_ANALYST_ROLE;

-- Grant USAGE on new procedures
GRANT USAGE ON PROCEDURE ANALYTICS.SP_PRODUCT_MATCH(VARCHAR) TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT USAGE ON PROCEDURE ANALYTICS.SP_PRICE_OPTIMIZER(VARCHAR, VARCHAR) TO DATABASE ROLE INSURANCE_ANALYST_ROLE;
GRANT USAGE ON PROCEDURE ANALYTICS.SP_MARKET_FORECAST(VARCHAR, VARCHAR) TO DATABASE ROLE INSURANCE_ANALYST_ROLE;

-- ############################################################################
-- Grant USAGE on new agents
-- ADMIN inherits all child roles, so granting to ADMIN covers all
-- ############################################################################

GRANT USAGE ON AGENT ANALYTICS.UNIFIED_ENTERPRISE_AGENT TO DATABASE ROLE INSURANCE_ADMIN_ROLE;
GRANT USAGE ON AGENT ANALYTICS.MARKET_INTELLIGENCE_AGENT TO DATABASE ROLE INSURANCE_ADMIN_ROLE;
GRANT USAGE ON AGENT ANALYTICS.PRICE_OPTIMIZATION_AGENT TO DATABASE ROLE INSURANCE_ADMIN_ROLE;
GRANT USAGE ON AGENT ANALYTICS.PRODUCT_MATCHING_AGENT TO DATABASE ROLE INSURANCE_ADMIN_ROLE;

-- Also grant to EXEC role (executives need access to all agents)
GRANT USAGE ON AGENT ANALYTICS.UNIFIED_ENTERPRISE_AGENT TO DATABASE ROLE INSURANCE_EXEC_ROLE;
GRANT USAGE ON AGENT ANALYTICS.MARKET_INTELLIGENCE_AGENT TO DATABASE ROLE INSURANCE_EXEC_ROLE;
GRANT USAGE ON AGENT ANALYTICS.PRICE_OPTIMIZATION_AGENT TO DATABASE ROLE INSURANCE_EXEC_ROLE;

-- UW role gets pricing and product matching agents
GRANT USAGE ON AGENT ANALYTICS.PRICE_OPTIMIZATION_AGENT TO DATABASE ROLE INSURANCE_UW_ROLE;
GRANT USAGE ON AGENT ANALYTICS.PRODUCT_MATCHING_AGENT TO DATABASE ROLE INSURANCE_UW_ROLE;

-- ############################################################################
-- Grant MCP server access to database roles
-- ############################################################################

GRANT USAGE ON EXTERNAL MCP SERVER ANALYTICS.ATLASSIAN_MCP_SERVER TO DATABASE ROLE INSURANCE_ADMIN_ROLE;
GRANT USAGE ON EXTERNAL MCP SERVER ANALYTICS.ATLASSIAN_MCP_SERVER TO DATABASE ROLE INSURANCE_EXEC_ROLE;

-- ############################################################################
-- Verification
-- ############################################################################

-- Check grants on new tables
SHOW GRANTS ON TABLE ANALYTICS.PRODUCT_CATALOG;
SHOW GRANTS ON TABLE ANALYTICS.COMPETITOR_PRICING;
SHOW GRANTS ON AGENT ANALYTICS.UNIFIED_ENTERPRISE_AGENT;
