import { QueryClient } from '@tanstack/react-query';
import { executeSQL } from './snowflake-api';

const PREFETCH_QUERIES: Record<string, string> = {
  'exec-all': `
    WITH kpis AS (
      SELECT (SELECT SUM(PREMIUM_AMOUNT) FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES WHERE POLICY_STATUS='Active') AS TOTAL_PREMIUM,
        (SELECT SUM(REVENUE_AT_RISK) FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES) AS REVENUE_AT_RISK,
        (SELECT COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES WHERE POLICY_STATUS='Active') AS ACTIVE_POLICIES,
        (SELECT COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE CLAIM_STATUS IN ('Open','Under Investigation','Escalated')) AS OPEN_CLAIMS,
        (SELECT ROUND(AVG(DAYS_TO_RESOLVE),1) FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE DAYS_TO_RESOLVE IS NOT NULL) AS AVG_RESOLUTION,
        (SELECT COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE FRAUD_SCORE > 0.7) AS HIGH_RISK_CLAIMS,
        (SELECT SUM(CLAIM_AMOUNT) FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE FRAUD_SCORE > 0.7) AS FRAUD_EXPOSURE,
        (SELECT COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS) AS TOTAL_CUSTOMERS
    ),
    pbt AS (SELECT 'PBT' AS SECTION, POLICY_TYPE AS DIM1, NULL AS DIM2, COUNT(*)::VARCHAR AS VAL1, SUM(PREMIUM_AMOUNT)::VARCHAR AS VAL2 FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES WHERE POLICY_STATUS='Active' GROUP BY POLICY_TYPE),
    cbs AS (SELECT 'CBS' AS SECTION, CLAIM_STATUS AS DIM1, NULL AS DIM2, COUNT(*)::VARCHAR AS VAL1, NULL AS VAL2 FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS GROUP BY CLAIM_STATUS),
    rbc AS (SELECT 'RBC' AS SECTION, RISK_CATEGORY AS DIM1, NULL AS DIM2, COUNT(*)::VARCHAR AS VAL1, SUM(REVENUE_AT_RISK)::VARCHAR AS VAL2 FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES GROUP BY RISK_CATEGORY),
    dqt AS (SELECT 'DQT' AS SECTION, TABLE_NAME AS DIM1, SCORE_DATE::VARCHAR AS DIM2, OVERALL_SCORE::VARCHAR AS VAL1, NULL AS VAL2 FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES WHERE TABLE_NAME IN ('CUSTOMERS','POLICIES','CLAIMS','BILLING'))
    SELECT 'KPI' AS SECTION, TOTAL_PREMIUM::VARCHAR AS DIM1, REVENUE_AT_RISK::VARCHAR AS DIM2, ACTIVE_POLICIES::VARCHAR||'|'||OPEN_CLAIMS::VARCHAR||'|'||AVG_RESOLUTION::VARCHAR AS VAL1, HIGH_RISK_CLAIMS::VARCHAR||'|'||FRAUD_EXPOSURE::VARCHAR||'|'||TOTAL_CUSTOMERS::VARCHAR AS VAL2 FROM kpis
    UNION ALL SELECT * FROM pbt UNION ALL SELECT * FROM cbs UNION ALL SELECT * FROM rbc UNION ALL SELECT * FROM dqt`,
  'kpi-all': `
    SELECT 'Executive' AS PILLAR, 'Premium Revenue' AS LABEL, TO_VARCHAR(SUM(PREMIUM_AMOUNT),'$999,999,999') AS VALUE, 'up' AS TREND FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES WHERE POLICY_STATUS='Active'
    UNION ALL SELECT 'Executive','Active Policies',TO_VARCHAR(COUNT(*)),'up' FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES WHERE POLICY_STATUS='Active'
    UNION ALL SELECT 'Executive','Total Customers',TO_VARCHAR(COUNT(*)),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS
    UNION ALL SELECT 'Executive','Total Coverage',TO_VARCHAR(SUM(COVERAGE_AMOUNT),'$999,999,999'),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES WHERE POLICY_STATUS='Active'
    UNION ALL SELECT 'Executive','Revenue at Risk',TO_VARCHAR(SUM(REVENUE_AT_RISK),'$999,999,999'),'down' FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES
    UNION ALL SELECT 'Executive','Outstanding Balance',TO_VARCHAR(SUM(OUTSTANDING_BALANCE),'$999,999,999'),'down' FROM INSURANCE_AI_HUB.ANALYTICS.BILLING
    UNION ALL SELECT 'Claims','Total Claims Filed',TO_VARCHAR(COUNT(*)),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS
    UNION ALL SELECT 'Claims','Open Claims',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE CLAIM_STATUS IN ('Open','Under Investigation','Escalated')
    UNION ALL SELECT 'Claims','Avg Resolution Days',TO_VARCHAR(ROUND(AVG(DAYS_TO_RESOLVE),1)),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE DAYS_TO_RESOLVE IS NOT NULL
    UNION ALL SELECT 'Claims','Total Claim Amount',TO_VARCHAR(SUM(CLAIM_AMOUNT),'$999,999,999'),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS
    UNION ALL SELECT 'Claims','Total Approved',TO_VARCHAR(SUM(APPROVED_AMOUNT),'$999,999,999'),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE APPROVED_AMOUNT IS NOT NULL
    UNION ALL SELECT 'Claims','Fraud-Flagged Claims',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE FRAUD_FLAG=TRUE
    UNION ALL SELECT 'Fraud','High-Risk Claims (>0.7)',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE FRAUD_SCORE>0.7
    UNION ALL SELECT 'Fraud','Fraud Exposure',TO_VARCHAR(SUM(CLAIM_AMOUNT),'$999,999,999'),'down' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE FRAUD_SCORE>0.7
    UNION ALL SELECT 'Fraud','Fraud-Flagged',TO_VARCHAR(COUNT(*)),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE FRAUD_FLAG=TRUE
    UNION ALL SELECT 'Fraud','Avg Fraud Score',TO_VARCHAR(ROUND(AVG(FRAUD_SCORE),2)),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS
    UNION ALL SELECT 'Fraud','Under Investigation',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE CLAIM_STATUS='Under Investigation'
    UNION ALL SELECT 'Fraud','Escalated Claims',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS WHERE CLAIM_STATUS='Escalated'
    UNION ALL SELECT 'Underwriting','Avg Loss Ratio',TO_VARCHAR(ROUND(AVG(LOSS_RATIO),2)),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES
    UNION ALL SELECT 'Underwriting','At-Risk Policies',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES
    UNION ALL SELECT 'Underwriting','Avg Risk Score',TO_VARCHAR(ROUND(AVG(RISK_SCORE),2)),'stable' FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES
    UNION ALL SELECT 'Underwriting','Avg Churn Prob',TO_VARCHAR(ROUND(AVG(CHURN_PROBABILITY),2)),'down' FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES
    UNION ALL SELECT 'Underwriting','Avg Credit Score',TO_VARCHAR(ROUND(AVG(CREDIT_SCORE))),'up' FROM INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS
    UNION ALL SELECT 'Underwriting','High-Risk Tier %',TO_VARCHAR(ROUND(COUNT(CASE WHEN RISK_TIER IN ('High','Very High') THEN 1 END)*100.0/COUNT(*),1))||'%','stable' FROM INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS
    UNION ALL SELECT 'Data Trust','Avg DQ Score',TO_VARCHAR(ROUND(AVG(OVERALL_SCORE),1)),CASE WHEN AVG(OVERALL_SCORE)>=85 THEN 'up' ELSE 'down' END FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES WHERE SCORE_DATE=(SELECT MAX(SCORE_DATE) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES)
    UNION ALL SELECT 'Data Trust','Failed Rules',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS WHERE STATUS='FAIL' AND EXECUTION_DATE=(SELECT MAX(EXECUTION_DATE) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS WHERE STATUS='FAIL')
    UNION ALL SELECT 'Data Trust','Critical Columns',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_COLUMN_HEALTH WHERE HEALTH_STATUS='Critical'
    UNION ALL SELECT 'Data Trust','Warning Columns',TO_VARCHAR(COUNT(*)),'down' FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_COLUMN_HEALTH WHERE HEALTH_STATUS='Warning'
    UNION ALL SELECT 'Data Trust','Total DQ Rules',TO_VARCHAR(COUNT(*)),'stable' FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RULES WHERE ACTIVE_FLAG=TRUE
    UNION ALL SELECT 'Data Trust','Tables Monitored',TO_VARCHAR(COUNT(DISTINCT TABLE_NAME)),'stable' FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES`,
  'gov-all': `
    WITH scores AS (SELECT 'SCR' AS SECTION, TABLE_NAME AS C1, OVERALL_SCORE::VARCHAR AS C2, COMPLETENESS_SCORE::VARCHAR AS C3, ACCURACY_SCORE::VARCHAR AS C4, CONSISTENCY_SCORE::VARCHAR AS C5, TIMELINESS_SCORE::VARCHAR AS C6, RULES_PASSED::VARCHAR AS C7, RULES_FAILED::VARCHAR AS C8, TREND AS C9 FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES WHERE SCORE_DATE=(SELECT MAX(SCORE_DATE) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES)),
    failures AS (SELECT 'FAIL' AS SECTION, r.TARGET_TABLE||'.'||r.TARGET_COLUMN AS C1, rl.RULE_NAME AS C2, rl.SEVERITY AS C3, r.PASS_RATE::VARCHAR AS C4, r.FAILED_RECORDS::VARCHAR AS C5, COALESCE(LEFT(r.ERROR_SAMPLE,120),'') AS C6, NULL AS C7, NULL AS C8, NULL AS C9 FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS r JOIN INSURANCE_AI_HUB.DATA_QUALITY.DQ_RULES rl ON r.RULE_ID=rl.RULE_ID WHERE r.STATUS='FAIL' AND DATE(r.EXECUTION_DATE)=(SELECT MAX(DATE(EXECUTION_DATE)) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS WHERE STATUS='FAIL')),
    trend AS (SELECT 'TRD' AS SECTION, TABLE_NAME AS C1, SCORE_DATE::VARCHAR AS C2, OVERALL_SCORE::VARCHAR AS C3, NULL AS C4, NULL AS C5, NULL AS C6, NULL AS C7, NULL AS C8, NULL AS C9 FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES WHERE TABLE_NAME IN ('CUSTOMERS','POLICIES','CLAIMS','BILLING','AGENTS'))
    SELECT * FROM scores UNION ALL SELECT * FROM failures UNION ALL SELECT * FROM trend ORDER BY SECTION, C1`,
  'admin-all': `SELECT CURRENT_USER()::VARCHAR AS CUR_USER, CURRENT_ROLE()::VARCHAR AS CUR_ROLE, CURRENT_WAREHOUSE()::VARCHAR AS CUR_WH, CURRENT_DATABASE()::VARCHAR AS CUR_DB`,
};

export async function prefetchAllDashboardData(queryClient: QueryClient) {
  const promises = Object.entries(PREFETCH_QUERIES).map(async ([key, sql]) => {
    try {
      const result = await executeSQL(sql);
      queryClient.setQueryData(['snowflake', key], result);
    } catch (err) {
      console.warn(`Prefetch ${key} failed:`, err);
    }
  });
  await Promise.all(promises);
}
